### PR TITLE
Add VPN_CONFIG_FILE option

### PR DESCRIPTION
**Pull request by dngray**
Closes: https://github.com/wfg/docker-openvpn-client/issues/20

### CODE REVIEW

**Comment by wfg** [comment]
@dngray let's get this rebased to master and I'll merge it.

**Comment by dngray** [comment]
Hmm, there does seem to be an issue with the `modified` config being generated.

```

 ---- Running with the following variables ----
 Kill switch: on
 HTTP proxy: off
 SOCKS proxy: off
 Allowing subnets: 192.168.7.0/24,192.168.4.0/24
 Using OpenVPN log level: 3
 Using configuration file: vpn_config.conf
 Creating vpn_config.conf.modified and making required changes to that file.
 cp: can't stat 'vpn_config.conf': No such file or directory
 sed: vpn_config.conf.modified: No such file or directory
 Changes made.

 Creating VPN kill switch and local routes.
 Allowing established and related connections...
 Allowing loopback connections...
 Allowing Docker network connections...
 Allowing specified subnets...
 RTNETLINK answers: File exists
 Allowing remote servers in configuration file...
 grep: vpn_config.conf.modified: No such file or directory
 grep: vpn_config.conf.modified: No such file or directory
 grep: vpn_config.conf.modified: No such file or directory
   Using:
 dig: '' is not a legal name (unexpected end of input)
 Allowing connections over VPN interface...
 Preventing anything else...
 iptables rules created and routes configured.

 Running OpenVPN client.

 Options error: In [CMD-LINE]:1: Error opening configuration file: vpn_config.conf.modified
 Use --help for more information.
```

**Comment by dngray** [comment]
Looks good to go.

**Comment by wfg** [comment]
Awesome. Thanks for the contribution!

**Pull request merged**
